# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsMetaData',
            fields=[
                ('blogId', models.IntegerField(primary_key=True, serialize=False)),
                ('publishingDate', models.DateField(default=datetime.datetime(2018, 7, 23, 20, 56, 23, 595506))),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('blogId', models.IntegerField(primary_key=True, serialize=False)),
                ('sequenceNo', models.IntegerField()),
                ('tag', models.CharField(max_length=15)),
                ('innerHTML', models.CharField(max_length=5000)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
