# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedExperiences', '0002_auto_20180808_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elements',
            name='blogId',
            field=models.IntegerField(),
        ),
    ]
