# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedExperiences', '0003_auto_20180809_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmetadata',
            name='author',
            field=models.CharField(default='Team TGS', max_length=50),
        ),
        migrations.AddField(
            model_name='blogsmetadata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 0, 33, 45, 545268)),
        ),
        migrations.AddField(
            model_name='blogsmetadata',
            name='previewImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogsmetadata',
            name='previewText',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
