# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-23 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedExperiences', '0005_auto_20180822_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmetadata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 23, 22, 50, 5, 793985)),
        ),
        migrations.AlterField(
            model_name='blogsmetadata',
            name='previewImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
