# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-23 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedExperiences', '0006_auto_20180823_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmetadata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 23, 23, 3, 53, 922765)),
        ),
        migrations.AlterField(
            model_name='blogsmetadata',
            name='previewImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
